spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_manager
    username: postgres
    password: QWERTasdfzxcv271828
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true